apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/aleks_saul/hello_world:latest