apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  - name: helloworld
    port: 1558
    targetPort : 80
