apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: quay.io/alekssaul/helloworld:latest